### ISSUE TITLE
Предложение: de_faq -> Deutschland-FAQ

### ISSUE THREAD

**Issue by stanislaw** [ewgRa/de_faq#146]
Приветствую!

Заголовок говорит сам за себя: я полагаю, этот репозиторий заслуживает более полного солидного названия на Github.

P.S. Это мое частное мнение, никому не навязываю, но предполагаю солидарность :)

Спасибо за внимание.

**Comment by alexandr-g** [comment]
Я за переименование на что-то более конструктивное / descriptive, но `Deutschland-FAQ` мне не нравится 👻

**Comment by stanislaw** [comment]
Есть еще очевидный вариант: Germany-FAQ. Судя по многозначительному молчанию, мое предложение не всем по душе ;)

**Comment by dstoianov** [comment]
перфекционистов мало здесь

**Comment by ewgRa** [comment]
Germany-FAQ слишком сложно запоминать и их ну очень много.

Если честно, не вижу практического смысла, Germany-FAQ ничем не солиднее de_faq, ну и за солидностью никто не гонится.

Плюсы неочевидны, минусов много, поэтому закрываю.

**Comment by stanislaw** [comment]
Достаточно справедливо и ожидаемо. Спасибо за внимание :)
