### ISSUE TITLE
Регистрация в банке Number26

### ISSUE THREAD

**Issue by BohdanTkachenko** [ewgRa/de_faq#147]
В статье сказано, что не получится имея украинкий паспорт открыть счет в Number26 с помощью видео-идентификации. Может мне просто повезло, но я видео-идентификацию прошел. Проверяющий просил меня покрутить мой паспорт под разными углами, искал там какие-то метки, не знаю нашел он их там или нет, но процедуру я прошел.

**Comment by oleksiikyrychenko** [comment]
+2 опыта удачного прохождения - со старым (красный) и новым (синий с пластиковой страницей).

**Comment by l13t** [comment]
напарник делал карточку для себя и жены. оба с украинскими паспортами. тоже прошли проверку.

**Comment by stanislaw** [comment]
+1 опыт удачного прохождения. 

@BohdanTkachenko, сделаете Pull Request с обновленной информацией :) ?

**Comment by dollar2048** [comment]
с паспортом Беларуси не прошел.

**Comment by pingwinator** [comment]
+1 по верификации по украинскому биометрическому

**Comment by cacozzzz** [comment]
Успешно прошел видео верификацию с паспортом Казахстана.

**Comment by khmigor** [comment]
Приложение не позволяет пройти видео-идентификацию для украинских граждан. В банке подтвердили, что еще недавно было можно, но больше (октябрь 2019) никакие украинские паспорта они не принимают.

**Comment by okainov** [comment]
@khmigor  PR welcome :)
