### ISSUE TITLE
Где базовый репозиторий?

### ISSUE THREAD

**Issue by pboettcher** [ewgRa/de_faq#152]
Сделал pull-request Ярославу Попову в репозиторий de_faq, а он ррраз, и скрыл его. Предполагаю, что не по причине написанного мною, а потому, что его репозиторий являлся клоном. Где тот базовый репозиторий, в который можно делать pull requests?

**Comment by nkaraman** [comment]
Это он и есть :)

**Comment by f2404** [comment]
@pboettcher У форков под названием написано "forked from repo/name".

**Comment by ewgRa** [comment]
@pboettcher да, это базовый. У Дениса форк, он там пишет более детально про все, с предысториями и т.п.
