### ISSUE TITLE
Онлайн банки

### ISSUE THREAD

**Issue by nnnikolay** [ewgRa/de_faq#178]
Добрый день.

Из тех, кто пользуется каким-то онлайн банком, есть ли где англоязычный суппорт? и UI?

Спасибо.

**Comment by skarpovru** [comment]
db.com - на переключатель интерфейса на английский/немецкий. Суппорт по телефону говорит по английски, в офлайн офисах банка как повезет

**Comment by l13t** [comment]
ну вообще в любой структуре по телефону и онлайн "как повезет". из немного другой оперы имел негативный опыт общения с техподдержкой водафона.

из полезностей, к которым привык за время жизни в германии - перевожу сайты хромом на английский и потом уже читаю что там написано. т.к. перевод на русский/украинский крайне корявый получается.

**Comment by nnnikolay** [comment]
@skarpovru  у них очень урезанная английская версия
у них ужастный суппорт
и сам UI и его функционал просто капец :(
хуже банка я еще не видел, после двух лет работы с ними, хочу посмотреть на что-то более свежее, и более шустрое, во всех смыслах этого слова.

**Comment by nnnikolay** [comment]
@l13t соглсаен на все 100%, однако с переводом не всегда все так хорошо, и я не говорю о не работающем JS иногда после перевода :)

**Comment by greyblake** [comment]
https://n26.com/

**Comment by l13t** [comment]
@nnnikolay ну тут никто не обязан делать английскую версию сайта. так что с этим надо мириться.

**Comment by nnnikolay** [comment]
@l13t так я их и не обязываю) просто информацию собираю.
