### ISSUE TITLE
Уведомление о банковском счете

### ISSUE THREAD

**Issue by fallart** [ewgRa/de_faq#186]
"Если вы являетесь валютным резидентом, то есть хотя бы 1 раз за 365 дней были в России"
на самом деле немного не так, по крайней мере по информации что я нашел:
статья 207 НК:"Налоговыми резидентами признаются физические лица, фактически находящиеся в Российской Федерации не менее 183 календарных дней в течение 12 следующих подряд месяцев"

**Comment by skarpovru** [comment]
Валютный резидент != Налоговый резидент
Закон об отчете по счетам распространяется именно на валятных резидентов. Налоговый тут не при чем

**Comment by fallart** [comment]
да, действительно, ошибся. прошу прощения
