### ISSUE TITLE
Guidlines

### ISSUE THREAD

**Issue by oleksiikyrychenko** [ewgRa/de_faq#188]
Наши котрибуторы жалуються, что в проекте нету нормальных гидлайнов.
Предлагаю их завести, чтобы было ясно о чем тут можно писать и как. 
Например, что тут не личный дневник, а ответы на часто задаваемые вопросы, инструкции как что делать. У меня есть видиние, что каждая страница и подраздел должен отвечать на какой-то вопрос. Ранее уже обсуждалось, что информация в стиле странице на википедии, не очень интересна, потому что это информация, а не ответ на вопрос. Потому предлагаю как-то понятно объяснить что есть de_faq и чем он не есть.

**Comment by ewgRa** [comment]
Гайдлайны должны быть полезны, да. А кто где жалуется и на что конкретно? Давно уже вроде не было ситуаций когда PR отклонялись.

> У меня есть видиние, что каждая страница и подраздел должен отвечать на какой-то вопрос. 
В целом сейчас так и есть по большей части.

Реорганизация страниц давно в планах, но руки не доходят, и если честно не знаю когда дойдут. Там немало переписывать и реорганизовывать.

**Comment by l13t** [comment]
проблемы вроде бы только с проверкой орфографии.

**Comment by olexiyk** [comment]
@ewgRa почитай, если интересно https://github.com/ewgRa/de_faq/pull/185

**Comment by ewgRa** [comment]
@olexiyk спасибо, почитал, постараюсь сегодня написать гайдлайн.

**Comment by olexiyk** [comment]
ок, а еще неплохо бы сразу и процесс внесения изменений в гайдлайн. то есть, пул-реквесты в статьи принимаются, если они соответсвуют гайдлайну, а пул-реквесты в гайдлайн принимаются по какому-то другому принципу.

**Comment by ewgRa** [comment]
Написал, https://github.com/ewgRa/de_faq/pull/193

Предлагаю начать с такого и посмотреть как пойдет. Просьба отписатья в Pull request, что добавить, что убрать, все ли ок.

**Comment by ewgRa** [comment]
смержил
