### ISSUE TITLE
Вопросы

### ISSUE THREAD

**Issue by GodfatherThe** [ewgRa/de_faq#205]
Добрый день,

Не нашел, где еще можно написать, "обсуждений" не видно, поэтому пишу так. Есть ли что-то похожее, но с информацией про Мюнхен? А то информация реально полезная, понятно, что в целом верная для всей страны, но явно заметно, что упор при написании делался на Берлин: адреса, ссылки, карты - все про Берлин.

**Comment by l13t** [comment]
изначально это была "документация" по берлину. но возможно автор не будет против дополнения информацией по другим городам.

**Comment by l13t** [comment]
@ewgRa кстати, а если подобное сделать при помощи бранчей? простите мои админские замашки (:

**Comment by ewgRa** [comment]
@l13t мне кажется бранчи будет сложно поддерживать. По крайней мере я точно не найду времени поддерживать их актуальными, разрешать конфликты и т.п. Но автор судя по всему спросил просто есть ли где-то такая информация.

@GodfatherThe вопрос в том - есть ли такая информация где бы то ни было? или вопрос был в другом?

Думаю вряд ли, но я не искал никогда. Здесь подобного для Мюнхена нету, потому что контрибутеры в основном из Берлина, соответственно перекос на Берлин.

**Comment by l13t** [comment]
@ewgRa я написал, а потом понял что сморозил глупость.

**Comment by GodfatherThe** [comment]
@ewgRa мне почему-то казалось, что комьюнити тут из разных городов, пусть даже большинство из Берлина, но есть народ и из других мест. Собственно, насколько я знаю, Мюнхен с Берлином - два самых популярных города для переезда айтишникам. Если я ошибся и тут именно берлинское комьюнити - извините, в таком случае не подскажете, есть ли что-то подобное по Мюнхену?

**Comment by ewgRa** [comment]
@GodfatherThe вот что удалось раздобыть: 

Теллеграмм группа: https://t.me/joinchat/AAAAAEB2xAPfsYsDipSlew
Wiki: http://ponaehali.de/

Есть скайп чат, но он по инвайтам.

**Comment by ewgRa** [comment]
Сделал PR для этих ссылок: https://github.com/ewgRa/de_faq/pull/206

**Comment by GodfatherThe** [comment]
Спасибо!

**Comment by ewgRa** [comment]
пожалуйста
