### ISSUE TITLE
Конвертация blue card в первые 18 месяцев

### ISSUE THREAD

**Issue by tdurova** [ewgRa/de_faq#219]
Слышала о волшебной возможности конвертировать blue card одной страны, которой еще нет 24 месяцев на блукард другой страны. Как это делать?

`To change jobs during the first two years of arrival, a request should be filed with the competent
authorities, and the decision of the authorities must be complied with. ` [Взяла отсюда](https://www.eaccny.com/wp-content/uploads/2016/06/The-EU-Blue-Card-Working-in-Europe.pdf)

**Comment by olexiyk** [comment]
Параграф, который вы привели, имеет отношение к изменению работы в первые два года. При подаче, у вас уже должна быть работа, вот если она поменялась, есть необходимость уведомить компетентный орган.

Конвертации не существует. Обладатель БК может подает все те же документы, что и остальные люди, которые БК не обладают.

**Comment by olexiyk** [comment]
В чате была дискуссия.  
ну вот в кратком изложении директивы ЕС написано так:
> After 18 months’ legal residence, an EU Blue Card holder benefits from some facilitation to move to another EU country. Provided they comply again with the admission criteria, they can be allowed to start working already before a decision is taken, and family members can join them immediately.

в самой директиве (ст. 18) так:
> 1. After eighteen months of legal residence in the first Member State as an EU Blue Card holder, the person concerned and his family members may move to a Member State other than the first Member State for the purpose of highly qualified employment under the conditions set out in this Article.
> 2.   As soon as possible and no later than one month after entering the territory of the second Member State, the EU Blue Card holder and/or his employer shall present an application for an EU Blue Card to the competent authority of that Member State and present all the documents proving the fulfilment of the conditions set out in Article 5 for the second Member State. The second Member State may decide, in accordance with national law, not to allow the applicant to work until the positive decision on the application has been taken by its competent authority.
> 3.   The application may also be presented to the competent authorities of the second Member State while the EU Blue Card holder is still residing in the territory of the first Member State.

То есть можно переехать и на месте подать на местный БК в течении месяца. Работать можно начинать сразу же, если это не запрещено в стране переезда. 
Судя по всему, надо уточнять об этом процессе, в компетентном ведомстве страны, куда собрались ехать.

**Comment by tdurova** [comment]
А срок работы в первой стране будет засчитан? Нужно ли будет выезжать за
пределы Евросоюза для подачи заявлений? Какие действия требуются от
работодателя в моем случае?

**Comment by olexiyk** [comment]
У вас вопрос конкретно по переезду из какой-то страны в какую-то или вообще?

1. Засчитан куда? Для [DA-EU](https://de.wikipedia.org/wiki/Erlaubnis_zum_Daueraufenthalt-EU_(Deutschland)) должен быть засчитан. Пенсионные отчисления тоже должно быть возможно перенести из другой страны ЕС. 

2. Смотрите выше - можно приехать в страну и течении месяца подать заявление на месте. 

3. От работодателя наверное как обычно: подписанный с вами трудовой договор. Ну ещё, по-моему, описание вакансии зачем-то требуют в Германии. Конечно же, зарплата должна выше определенного лимита, думаю, в каждой стране ЕС, этот лимит свой.

**Comment by ewgRa** [comment]
закрываю, если остались вопросы, можно спросить в конференциях https://github.com/ewgRa/de_faq/blob/master/README.md
