### ISSUE TITLE
Недоступна ссылка

### ISSUE THREAD

**Issue by RomanKrasavtsev** [ewgRa/de_faq#220]
На странице https://github.com/ewgRa/de_faq/blob/master/%D0%A0%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F%20%D0%BC%D0%B5%D1%81%D1%82%D0%B0%20%D0%B6%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D1%82%D0%B2%D0%B0.md

в предложении "Если всё же у кого-то остался ваш старый адрес, они могут присылать вам на него письма (в том числе очень важные)." недоступна ссылка для слова "письма"

**Comment by ewgRa** [comment]
@RomanKrasavtsev спасибо за репорт

закрываю, проблема решилась PR под ругому вопросу.
