### ISSUE TITLE
Разделение текстов Берлин\Мюнхен

### ISSUE THREAD

**Issue by GodfatherThe** [ewgRa/de_faq#222]
Предлагаю как-нибудь формализовать правила, как разделять разные штуки по городам. Примеры - адреса Burgerburo, специфика записей и проч. В своем ПР я просто писал "Берлин:" и "Мюнхен:", но это не особо солидно, хотелось бы более красивого чего-нибудь. 

Как пример - можно поиспользовать флаги, как кое-где сделано для РФ\Германии\Украины, тут можно использовать герб Мюнхена и Берлина. 

Что думаете на эту тему?

**Comment by GodfatherThe** [comment]
Типа так:
Адрес центрального Burgerburo:
![image](https://cloud.githubusercontent.com/assets/918446/24380516/05abb2ea-134c-11e7-8613-2b0dfad1726b.png)  - Orleansstraße 50
![image](https://cloud.githubusercontent.com/assets/918446/24380526/1dcc7d14-134c-11e7-8c5e-023e85e5dc9c.png) - Karl-Marx-Allee 31

Хотя тоже как-то некрасиво смотрится...

**Comment by ewgRa** [comment]
Я за гербы лично. Но это не уверсальное решение, если список городов начнет увеличиваться, то в рамках гитхаба это уже видимо не решить нормально. По идее нужен "select", но это уже надо делать сторонний ресурс.

**Comment by GodfatherThe** [comment]
Ну пока вроде тренд "понаехавших" - это только Берлин и Мюнхен, остальные города единицы. Поэтому на данном этапе должно быть нормально.

**Comment by ewgRa** [comment]
Пока можно гербами, если увеличиться список городов, дальше будем думать
