### ISSUE TITLE
Перевоз личного имущества из другой страны Евросоюза в Германию

### ISSUE THREAD

**Issue by tdurova** [ewgRa/de_faq#232]
Планирую сменить резиденство с одной страны ЕС (Латвия) на немецкое, гражданство российское. Планирую ввезти автомобиль, купленный недавно у частного лица, который зарегестрирован в Латвии и налоги платили в Латвии. Будет ли это авто попадать под личное имущество? Нужны ли будут транзитные номера? Надо ли делать растоможку? Какие налоги надо платить?

**Comment by ewgRa** [comment]
Лучше всего обратиться с вопросом в таможню.

Латвия вроде как страна ЕС, то есть таможенной границы нету, по идее машина может спокойно ездить тут на литовских номерах. Если есть прям желание на немецкие номера ее поставить - то особых проблем быть не должно. Но опять же, лучше спрашивать на таможне и там где ставят авто на учет.

Можно еще попробовать спросить на авто-форумах.

**Comment by cmyker** [comment]
Знаю точно что машину надо переоформлять на немецкую регистрацию если ты
проживаешь в Германии, т.к. налог платить за нее нужно здесь.
