### ISSUE TITLE
Смена основания для владения Блукард (Blue card)

### ISSUE THREAD

**Issue by tdurova** [ewgRa/de_faq#233]
Если у двух супругов независимые Blue card одной страны ЕС, и они переезжают в другую страну ЕС (Германия), при этом работу пока имеет только один из супругов => второй супруг планирует получить блукард на основе блукард супруга, то что просиходит с его существующей блукард? Какой процесс?

**Comment by ewgRa** [comment]
Самое правильное - обратиться в немецкий АБХ, они скажут.

Все остальное требует тщательного чтения законов, и не факт что там в законе все это прописано.

Интуиция подсказывает что это будет совсем другой Blue Card, в другой стране.
Попробуйте в чатах поспрашивать, там есть вроде те, кто переезжал из одной страны ЕС в другую, может они подскажут.
