### ISSUE TITLE
Налоговый вычет при покупке жилья/ипотеке

### ISSUE THREAD

**Issue by tdurova** [ewgRa/de_faq#244]
Влияет ли покупка жилья/ипотека на уменьшение налоговой базы? Есть ли какие то специальные программы для молодых семей ищи еще кого-нибудь, облегчающие покупку жилья?

**Comment by ewgRa** [comment]
Про программы не слышал. Насчет налогов... честно говоря тоже не слышал, но все может быть.

Лучше спросить у какого-нибудь бератора, они по такому вопросу по идее бесплатно проконсультируют по телефону.

Личный опыт можно в slack чате поспрашивать, там есть канал taxes.

Если узнаете какую-то информацию, будем рады если поделитесь.
