### ISSUE TITLE
Забор пенсии при потере резиденства/переезде на ПМЖ в другую страну

### ISSUE THREAD

**Issue by tdurova** [ewgRa/de_faq#249]
Слышала/читала о возожности "изъять" пенсию при выезде из страны / переезде в другую страну. Как это происходит на практике и какой алгоритм действий? Таким образом можно забрать только часть пенсии, а-ля "второй уровень" или всю?

**Comment by ewgRa** [comment]
Тоже слышал-читал, но лично таких не знаю. По идее надо с таким вопросом обращаться в пенсионный фонд.

Если узнаете как это делается - будем рады если поделиесь какой-либо информацией.

Привет!

Из личного опыта, то что я читал, тех. осмотр и подготовку к нему лучше проходить в разных местах. Потому что когда это в одном месте - они заинтересованы найти побольше проблем. Если в машинах не разбираетесь, то могут на ненужные работы подписать. 

Личный опыт можно в slack чате поспрашивать, может там кто сталкивался с таким и знает больше.
