### ISSUE TITLE
Ремонт автомобиля для прохождения тех. осмотра

### ISSUE THREAD

**Issue by tdurova** [ewgRa/de_faq#250]
Насколько выгодна такая услуга, какие стоимости, какие фирмы можете порекомендовать (Берлин)? Или они как то намеренно могут "усугубить" ситуацию и увеличить список проблем, которые надо устранить. для прохождения ТО?

**Comment by ewgRa** [comment]
Привет!

Из личного опыта, то что я читал, тех. осмотр и подготовку к нему лучше проходить в разных местах. Потому что когда это в одном месте - они заинтересованы найти побольше проблем. Если в машинах не разбираетесь, то могут на ненужные работы подписать. 

Личный опыт можно в slack чате поспрашивать, там есть канал auto.

**Comment by nnnikolay** [comment]
@ewgRa а можно ссылочку на канал?

**Comment by oleksiikyrychenko** [comment]
Отсюда https://github.com/ewgRa/de_faq 
> Чат в Slack: https://slack-files.com/T09S9JDU1-F0HHEG8PK-c9396c730a
а дальше там `#auto`
