### ISSUE TITLE
Нужно ли менять права, выданные в другой европейской стране

### ISSUE THREAD

**Issue by tdurova** [ewgRa/de_faq#251]
При длительном проживании (более полугода?) нужно получать немецкий права. Но некоторые товарищи с правами, выданными в других странах EU (Польша, Латвия) утверждают, что это делать не обязательно. Как дело обстоит по факту?

**Comment by GodfatherThe** [comment]
Без пруфов, но думаю, менять надо. Другой вопрос, что в случае прав ЕС,
скорее всего, это именно обмен - никаких экзаменов, пришли и обменяли
просто.

Best regards,
Oleg Kainov.

**Comment by tdurova** [comment]
В общем жду пруфы, даже на простой "обмен без экзаменов". Слышала, что раньше так было, но когда начался беспорядок на дорогах, то закон изменили и "простой обмен" вообще убрали.

**Comment by GodfatherThe** [comment]
Гугл? Вот вторая же ссылка:
>If you hold a driving licence issued by a Member State of the European Union (EU) or a state party to the Agreement on the European Economic Area (EEA), it will normally remain valid after you have taken up residence in the Federal Republic of Germany until the end of its period of validity. You must have a domestic driving licence – an International Driving Permit is not sufficient.

https://www.bmvi.de/SharedDocs/EN/Articles/LA/validity-foreign-driving-licences-in-germany.html

**Comment by nikolaykasyanov** [comment]
http://europa.eu/youreurope/citizens/vehicles/driving-licence/driving-licence-recognition-validity/index_en.htm, параграф Recognition of EU driving licences issued in exchange for a non‑EU licence.

**Comment by nikolaykasyanov** [comment]
Ну и детальнее: http://europa.eu/youreurope/citizens/vehicles/driving-licence/driving-licence-recognition-validity/germany/index_en.htm
