### ISSUE TITLE
Отказы без интервью при хорошем опыте работы (Берлин)

### ISSUE THREAD

**Issue by tdurova** [ewgRa/de_faq#252]
Кто-то сталкивался с такой ситуации? Хорошее резюме, большой опыт, есть разрешение на работу, рекомендации и тд, но даже не зовут на собеседования, присылают отказы.

**Comment by AlexDenisov** [comment]
Такое бывает, да. В чем смысл вопроса? Какой ответ вы ожидаете здесь услышать? :)

**Comment by GodfatherThe** [comment]
Ну это вроде не "Берлин", а вообще в принципе в мире. Вроде как зачастую люди на 50 аппликейшенов получают 5 приглашений на собеседование, и потом 1 на очное, которое еще не факт, что превратится в оффер.

Если же у вас на 100 аппликейшенов 0 приглашений на интервью - зуб даю, у вас кривое резюме. Гуглите "как составить резюме", саммари - одна страничка, 0 персональной информации, 0 фото, релевантный опыт, упор на что сделали (а не "что делали").
