### ISSUE TITLE
Как быстро Ausländerbehörde назначает appointment  после получения документов от работодателя?

### ISSUE THREAD

**Issue by tdurova** [ewgRa/de_faq#255]
Работодатель является партнером Ausländerbehörde, к примеру 1 го числа он отправляет все документы в электронном виде в Ausländerbehörde, сколько дней АБХ их обрабатывает? Какого числа примерно будет назначен appointment?

**Comment by GodfatherThe** [comment]
Сомневаюсь, что это как-то связано с работодателем. Скорее всего в общем
порядке, поскольку в случае БК виза - есть та же БК, то по опыту термин
дают за месяц-полтора до окончания срока визы.

Best regards,
Oleg Kainov.

**Comment by tdurova** [comment]
У меня вообще нет визы и не будет, у меня блукард другой страны. 

Если работодатель партнер АБХ, то процесс идет каким то образом быстрее. так как все документы в электронном виде и работадель уже "авторизирован" там.

**Comment by GodfatherThe** [comment]
Если у вас БК другой страны, то вы должны будете получить БК Германии, очевидно. У меня есть сомнения, что на основании БК другой страны вы имеете право работать в Германии, поэтому придется ждать. В таком случае может и быстрее нескольких месяцев.
Да откуда у вас информация, что работодатель вообще контактирует с АБХ как-то? Если компания нанимает компанию-посредника для ведения вашего иммиграционного дела - так они точно также контактируют, как и вы бы сами общались.

**Comment by tdurova** [comment]
Есть понятия "партнерства работодателя" с АБХ или я ошибаюсь?

**Comment by franua** [comment]
реально уже напрягает этот чатик

**Comment by l13t** [comment]
нет такой штуки, скорее всего. в общую очередь со всеми документами и справка. но в первую очередь узнать у самого АБХ что они по этому поводу думают.
ну или у работодателя - он то на основании чего-то вам предложил работу.
