### ISSUE TITLE
ZAB соответсвие диплома, в каком виде отправляется решение

### ISSUE THREAD

**Issue by tdurova** [ewgRa/de_faq#256]
С трудовым контрактом по ускоренной процедуре делаю соответсвие диплома в ZAB, получила от них ответ:

> you statement of comparability will probably be sent to you in the
> course of next week.

Интересно, а в каком виде будет отправлен данный statement и кому? Мне, АБХ, работодателю? ПО обычной почте (как долго это будет идти в таком случае?) или в электронном виде? Statement нужен моему работодателю для завершения подачи всех нужных документов в АБХ.

**Comment by maxcold** [comment]
@tdurova issues не самое лучшее место для вопросов, для этого есть чаты в Skype или Slack

**Comment by tdurova** [comment]
Хорошо, тогда мне удалить?

**Comment by maxcold** [comment]
как владелец этого репозитория попросит, просто переместите обсуждение в какой-нибудь из чатов

**Comment by tdurova** [comment]
В итоге прислали в pdf + бумажный вариант обычной почтой.
