### ISSUE TITLE
Пояснение про социальное жилье (WBS)

### ISSUE THREAD

**Issue by karavayeu** [ewgRa/de_faq#270]
Было бы здорово добавить информацию о WBS в раздел [Квартирный вопрос](https://github.com/ewgRa/de_faq/blob/master/%D0%9A%D0%B2%D0%B0%D1%80%D1%82%D0%B8%D1%80%D0%BD%D1%8B%D0%B9%20%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81.md)
Из [офицального источника](https://service.berlin.de/dienstleistung/120671/) я понял, что отправить запрос на такую справку могут как минимум те, у кого есть вид на жительство хотя бы на год. При этом указан длинный список необходимых документов. 

Несмотря на то, что WBS-квартиры чаще всего в многоэтажках и предназначены для малоимущих, может быть эта информация на русском будет полезна.

**Comment by ewgRa** [comment]
@karavayeu было бы здорово, это да. Тут главное чтобы нашелся человек который готов на это потратить время и был в теме.

Пока я закрываю, если такой человек найдется, то всегда можно открыть pull request.
