### ISSUE TITLE
Визуальное обьяснение налоговых классов

### ISSUE THREAD

**Issue by l13t** [ewgRa/de_faq#281]
Попалась в инете в одной из групп фейсбука такая картинка: https://raw.githubusercontent.com/l13t/de_faq/master/files/nalogovyi_klass.jpg

Вопрос к народу - стоит ли ее добавлять в репозиторий и документацию?

**Comment by GodfatherThe** [comment]
А зачем?
1. Что такого в ней написано, чего не написано в репозитории?
2. Вы думаете, что люди, знающие немецкий, не могут сами погуглить на немецком?

**Comment by stanislaw** [comment]
На вопрос "зачем?" я бы ответил, что для наглядности. Я сделал то же самое для мусора: https://github.com/ewgRa/de_faq/pull/280.

**Comment by l13t** [comment]
собственно да, для наглядности. мне, например, проще воспринимать визуальную информацию вместо многабукаф.

**Comment by GodfatherThe** [comment]
Мой point в том, что в русскоязычный репозиторий вставлять непонятную немецкоязычную картинку смысла нет абсолютно никакого. Те, для кого не составляет проблем понять, могут сами погуглить. А те, кто читают репозиторий, скорее всего с первым множеством почти не пересекаются. Если бы вы перевели картинку, то был бы другой вопрос. 
Ну а легкость восприятия - спорный вопрос. Если это "многабукаф", то это пишуший криворук в 90% случаев, что не смог донести информацию понятно, а не проблема текстового донесения информации в принципе.

Я бы предложил идти от проблемы. У вас есть проблема понимания текущего текста? Где конкретно? Я вот глянул - мне все абсолютно понятно

> Холостой бездетный человек относится к 1-му классу. 
> Холостой человек с ребёнком (детьми) — ко 2-му.
> классы 4+4 обычно выгодны, когда оба супруга работают и получают примерно одинаковый доход.
> Классы 3+5 обычно выгодны, когда работает только один из супругов либо же доход второго супруга намного меньше
> 6-й класс назначается людям, имеющим больше одного места работы одновременно.

Что из этого вам кажется недостаточно детально объясненным?

**Comment by l13t** [comment]
абсолютно не согласен с "пишуший криворук в 90% случаев" - я в принципе подобные тексты не воспринимаю и это моя проблема, о которой я прекрасно знаю.
окей. точка зрения ваша услышана. хотелось бы еще альтернативных.

**Comment by stanislaw** [comment]
Вопрос к @GodfatherThe: 

Автор issue говорит, что ему визуальная информация помогает. Если будет и текст, **и** картинка - неужели вам это помешает?

**Comment by GodfatherThe** [comment]
@stanislaw я не вижу ценности в немецкоязычной картинке, не несущей никакой дополнительной информации, для комьюнити.

**Comment by AlexDenisov** [comment]
@GodfatherThe спасибо что ответили за все комьюнити 👍

**Comment by nnnikolay** [comment]
Накинулись на человека а у человека point не видите что-ли.

@GodfatherThe если день не задался, такое бывает, только картинка не виновата.

P.S. Картинку предлагаю оставить.

**Comment by oleksiikyrychenko** [comment]
@l13t переведите пожалуйста картинку. Вот я смотрю на картинку, а на ней текст. Ну правда, в чём смысл. Поддерживаю @GodfatherThe, хоть может он и выразил свою мысль в слегка агрессивной форме.

**Comment by nnnikolay** [comment]
@oleksiikyrychenko  если вы попытаетесь посмотреть на картинку не обращая внимая на текст (при условии что вы не знаете немецкого) станет и так все понятно на мой взгляд. Вот скажите что вам не ясно из картинки?

**Comment by oleksiikyrychenko** [comment]
@nnnikolay примерно ничего не ясно. Люди какие-то на всех картинках. Я не люблю такие вот ребусы. И даже текст прочитал и не смог понять что за 2 класс такой.

**Comment by nnnikolay** [comment]
@oleksiikyrychenko а вы простите какой професси/образовании?

нарисовано 5 взрослых людей с 5ю детьми, тут как бы намек либо на то что вы живете одно бл..дь семьей с 5ю детьми и 5ю взрослыми (что должно бы намекать на странные мысли), либо это все люди одинокие родители. Не ужели и правда в ступор ставит картинка? Это нахрен не ребус еще, это просто логика.

**Comment by oleksiikyrychenko** [comment]
@nnnikolay не переходите на личности и следите за выражениями

**Comment by nnnikolay** [comment]
Многоуважаемый, Олексий, а что в моем комментарии вам показалось личного? Я ведь просто объяснил вам логику любой подобной картинки. А вы, сразу удалять, право как ребёнок. Мне честно говоря все равно, хотите удаляйте картинку, хотите не напрягайте мозги, ваша жизнь вам решать. Аривидерчи.

P.S. чувствую и этот же комментарий будет удалён :)

**Comment by oleksiikyrychenko** [comment]
> а вы простите какой професси/образовании?
а вы? или вы меня собрались тут обсудить? спасибо не надо
> нарисовано 5 взрослых людей с 5ю детьми, тут как бы намек либо на то что вы живете одно бл..дь семьей с 5ю детьми и 5ю взрослыми (что должно бы намекать на странные мысли), либо это все люди одинокие родители. Не ужели и правда в ступор ставит картинка? Это нахрен не ребус еще, это просто логика
вы задали вопрос, что я вижу на картинке, я ответил. вам мой ответ не понравился, вы намекать на мои ограниченные способности к восприятию.
вы правда хотите продолжать обсуждения меня?
что вам не понравилось в просьбе перевести картинку? 
@nnnikolay, вот эта дискуссия, которую вы тут пытаетесь поддержать, совершенно уже не относится к теме, потому-то её и следовало бы прекратить. Вам ясно почему?

**Comment by trickii** [comment]
1. Разное восприятие существует, не вижу ничего, что может помешать предоставить информацию в виде текста для одних, картинки для других и аудио/видео с объяснением для третьих/четвертых (Первый результать на https://www.youtube.com/watch?v=LsfHba3wyIQ ютубе). Главное передача информации.
2. Хоть репозитории и рускоязычный, но про германию. Наличие немецких (довольно базовых) слов даже приветствуется. Всё равно осваивать придётся.

Минус только качество картинки и ужатость.

**Comment by nnnikolay** [comment]
@oleksiikyrychenko Да, Вы правы, я слишком резко отреагировал на достаточно странные (на мой взгляд) притензии к картинке. Не стоило так.

Только вот перевод картинки это зло. Вы же все равно будете учить немецкий рано или поздно вы к этому придете, так вот пусть лучше раньше чем позже. И для вновь прибывших тоже такая же история. Какой смысл в русской картинке? Ведь следующими придут рьяные любители Украинского, Беларуского и т.д. и что на все языки переводить? Вы живете в Германии, и язык тут один немецкий. Нравится вам это или нет, но надо привыкать. Тем более что описание по-русски все равно есть.

**Comment by l13t** [comment]
к слову, из того, что я вижу в телеграмовском чатике и слаке - часто на эту документацию отправляют людей, которые уже знают немецкий (поздние переселенцы или учившие немецкий). это небольшой апдейт.

**Comment by l13t** [comment]
окей. попробую перевести эту картинку

**Comment by l13t** [comment]
кстати, относительно сказанного @nnnikolay о учить немецкий и т.п. искать то потом инфу детальную вы все равно будете по немецким терминам.

**Comment by ewgRa** [comment]
@l13t "часто на эту документацию отправляют людей, которые уже знают немецкий" - основной кейз все-таки это люди, не знающие немецкого. У тех кто знает немецкий, или поздних переселенцев в основном все эти вопросы решены либо не вызывают затруднений.

Без знания немецкого имхо картинка может вызвать непонимание, лично я против картинки ничего не имею, если она будет переведена. На немецком скорее против.

**Comment by manme** [comment]
как картинка объяснит ситуацию: муж работает, жена нет. какой налоговый класс будет? или муж работает, жена учится и работает как воркштудент?

**Comment by ewgRa** [comment]
закрываю, если будет картинка переведена, можно оформить pull request.
