### ISSUE TITLE
Создать оглавление в README.md

### ISSUE THREAD

**Issue by lex111** [ewgRa/de_faq#286]
Добавить ссылки на все страницы в README.md, что-то вроде оглавления (для удобства)

**Comment by stanislaw** [comment]
Есть разного рода генераторы для этого. Я пользуюсь https://github.com/thlorenz/doctoc.

**Comment by GodfatherThe** [comment]
Где-то несколько месяцев назад я предлагал и даже ПР был) Отшили, "не тот формат" :)

**Comment by ewgRa** [comment]
см. https://github.com/ewgRa/de_faq/pull/226
