### ISSUE TITLE
Интернет+телефон

### ISSUE THREAD

**Issue by fetis** [ewgRa/de_faq#290]
Просится статья про интернет. Чтобы сбить шок, по сравнению с РФ.

Основные тезисы
- он хуевый, ибо почти везде DSL
- он дорогой
- в нагрузку получите еще и телефон
- роутер в подарок/в аренду. плюсы и минусы такого решения.

Перечислить основных провайдеров. Чек24, как было выяснено экспериментальным путем, лажает (возможно все проплачено)  и не показывает некоторых провайдеров, как доступных для подключения. Нужно проверять каждого на их сайте.

Указать что есть **лимит трафика**! OMG. 2017 на дворе

**Comment by GodfatherThe** [comment]
А еще месяц подключают. 
Роутер можно или не брать или за 0 самый стремный взять, и подключить его к своему (точнее, модем же - и модем подключать к своему нормальному роутеру)
Лимит трафика - ну тут просто читать внимательнее тариф надо, иногда бывает, да, но скорее исключение все-таки.
А еще тогда уж и про контракт написать - 95% только контракт минимум на год или два, оставшиеся 5% можно без контракта, но условия хуже/дороже

**Comment by fetis** [comment]
Чек24 реально херню порет. Показывает тарифы, которых уже нет (например для Telekom)

**Comment by sumerman** [comment]
интереса ради — а кто ещё без контракта кроме easybell?

**Comment by GodfatherThe** [comment]
@sumerman есть у 1&1 возможность без контракта подключаться. Интернет тот же с тем же тарифом, но остальные "плюшки" (возможно, никому и не нужные) пропадают, плюс они начинают хотеть больше денег за модем.
С контрактом - 0  за самый дешевый модем "проводной" (в кавычках, потому что только в прошивке блок вайфая)
Без контракта - 160 чтоли евро единоразово даже за самый дешевый модем.
Возможно, можно как-то отмазаться от этого, не пробовал.

**Comment by fetis** [comment]
@GodfatherThe А разве просто ADSL модем не дешевел выйдет? Или он как-то хитро залочен

**Comment by GodfatherThe** [comment]
Не понял вопроса. От провайдера девайс - это в большинстве случаев Adsl-модем + роутер в одном лице.

**Comment by fetis** [comment]
@GodfatherThe ты пишешь, что они заставляют купить девайс за 160 евро. Разве не дешевле будет купить модем на стороне или они залочены у них под сеть 1&1?

**Comment by GodfatherThe** [comment]
@fetis когда без контракта см https://dsl.1und1.de/dsl-ohne-vertragslaufzeit#tarife

> zuzüglich
1&1 DSL-Modem
für 0,– €/Monat
**zzgl. einmalig 149,99 €**
oder
1&1 WLAN-Router
für 2,99 €/Monat
**zzgl. einmalig 49,99 €**
oder
1&1 HomeServer
Speed
für 4,99 €/Monat
**zzgl. einmalig 99,99 €**

Как я понимаю, совсем отмазаться от железки не получится. Хотя я не пробовал, я решил для себя. что я ок с контрактом и взял бесплатный "проводной" модем (первая строчка как раз - когда ты на контракте, то этой единоразовой платы нет).

**Comment by l13t** [comment]
Иногда только устройства от прова дают полный функционал. Например, у моего
прова доксис модем-роутер. Только с ним возможна работа с стационарным
номером. Он конечно мало кому из нас нужен, но это как пример.

**Comment by DaVinciEngineer** [comment]
Внезапно: https://github.com/ewgRa/de_faq/pull/295
