### ISSUE TITLE
Перевести на английский?

### ISSUE THREAD

**Issue by karen2k** [ewgRa/de_faq#301]
Не смог найти аналогичного репозитория по-английски.
Было бы круто перевести, чтобы расширить аудиторию.
Что думаете?

**Comment by ewgRa** [comment]
Было бы хорошо, вопрос кто этим будет заниматься.

В англоязычной среде есть неплохой ресурс https://www.toytowngermany.com/

Там етсь в том числе форум довольно живой.

**Comment by karen2k** [comment]
@ewgRa можно требовать контрибьюшн сразу на двух языках и проверять во время билда
toytowngermany – отличный ресурс, но ищется преимущественно через google

**Comment by ewgRa** [comment]
@karen2k это нереально.

Во-первых не все умеют хорошо по-английски, во-вторых не все будут время тратить. На исправление ошибок и грамматики только в русской версии уходит много времени и во многих случаях приходится это делать самому.

Добавление английской версии будет означать - сделайте сами. В итоге возвращаемся к вопросу есть ли человек, который найдет мотивацию этим заниматься.

**Comment by karen2k** [comment]
убедили -)
