### ISSUE TITLE
неточности в Авто

### ISSUE THREAD

**Issue by fetis** [ewgRa/de_faq#318]
> Место сдачи экзамена:
>        Alboinstraße 56, 12103 Berlin

Это не единственное место. Сдаешь в Dekra или TÜV их много по городу

**Comment by fetis** [comment]
ДрайаНау подняли цены с 1 декабря

**Comment by GodfatherThe** [comment]
> Это не единственное место. Сдаешь в Dekra или TÜV их много по городу

Окей, если просто удалю и текстом "в городе есть несколько мест сдачи экзаменов"?

**Comment by fetis** [comment]
я бы оставил Dekra и  TÜV потому что сдать можно только у них. это называется prüfstelle

**Comment by ewgRa** [comment]
Новые цены drivenow - #325 

Места сдачи экзаменов - #324
