### ISSUE TITLE
Переезд

### ISSUE THREAD

**Issue by ewgRa** [ewgRa/de_faq#323]
Хотелось бы этот faq перевезти на https://github.com/ru-de/faq, а этот задепрекейтить и в последствии вообще удалить.

Несколько причин для этого шага: 

- Отвязать от моего аккаунта. Это повысит мотивацию контрибутеров, сейчас многие читатели думают, что этот faq в основном моя заслуга, и мне приходиться каждый раз подчеркивать, что это совместный труд большого количества людей. С https://github.com/ru-de/faq это станет очевидней.

- сделать faq более устойчивым и независимым от персонального аккаунта, если надо будет поменять ownerа, для всех это пройдет незаметно.

- ну и кучка мелких причин, типа мой аватар по ссылкам в скайпе и т.п.

Кто что думает?

**Comment by stanislaw** [comment]
Прекрасная идея!

**Comment by ewgRa** [comment]
добавил в readme оповещение

**Comment by ewgRa** [comment]
перетащил средствами git'а, все редиректы работают, так что просто поменялся линк

**Comment by fetis** [comment]
А issues похерились или у нас их реально было 0?

Иконку теперь можно сделать

**Comment by ewgRa** [comment]
@fetis нет, их реально стало 0. Их обычно немного. Большинство висят без движение какое-то время, я их закрываю.
