### ISSUE TITLE
Integrate Spell checker

### ISSUE THREAD

**Issue by ewgRa** [ewgRa/de_faq#34]
@see something like hunspell.sourceforge.net and hooks for git repo.

**Comment by pioneerit** [comment]
@ewgRa, @see: this is a good example of commit message checking hook:
https://gist.github.com/bean5/5c99498423b506afad5c

**Comment by andreytkachenko-home24** [comment]
А что кто-то правит файлы не напрямую в браузере ?

On 8 January 2016 at 10:19, Alexander <notifications@github.com> wrote:

> @ewgRa <https://github.com/ewgRa>, @see <https://github.com/see>: this is
> a good example of commit message checking hook:
> https://gist.github.com/bean5/5c99498423b506afad5c
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ewgRa/de_faq/issues/34#issuecomment-169944017>.
>



-- 

Andrey Tkachenko
Software Engineer

<https://app.adjust.io/aowvd8?campaign=app_DE_iOS_launch&adgroup=email_signature&creative=&deep_link=home24%3A%2F%2F&fallback=http%3A%2F%2Fwww.home24.de%2Fapp%2F>

*www.home24.de* <http://www.home24.de/>

Home24 AG | Greifswalder Straße 212-213 | 10405 Berlin | Deutschland
tel: +49 17 999 31509 | mail: andrey.tkachenko@home24.de

Vorstand: Domenico Cipolla, Dr. Philipp Kreibohm, Constantin Eis, Axel
Hefer,
Vorsitzender des Aufsichtsrats: Alexander Samwer
Sitz Berlin | Eingetragen beim Amtsgericht Berlin (Charlottenburg), HRB
167157 B

Diese Nachricht (inklusive aller Anhänge) ist vertraulich. Sie darf
ausschließlich durch den vorgesehenen Empfänger
und Adressaten gelesen, kopiert oder genutzt werden. Sollten Sie diese
Nachricht versehentlich erhalten haben, bitten
wir Sie, den Absender (durch Antwort-E-Mail) hiervon unverzüglich zu
informieren und die Nachricht zu löschen. Jede
unerlaubte Nutzung oder Weitergabe des Inhalts dieser Nachricht, sei es
vollständig oder teilweise, ist unzulässig. Bitte
beachten Sie, dass E-Mail-Nachrichten an den Absender nicht für
fristgebundene Mitteilungen geeignet sind.
Fristgebundene Mitteilungen sind daher ausschließlich per Post oder per
Telefax zu übersenden.

**Comment by pioneerit** [comment]
@andreytkachenko-home24, обижаешь. Все в консольке же :)

**Comment by andreytkachenko-home24** [comment]
Я только в браузере, эх село я....

On 8 January 2016 at 10:28, Alexander <notifications@github.com> wrote:

> @andreytkachenko-home24 <https://github.com/andreytkachenko-home24>,
> обижаешь. Все в консольке же :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ewgRa/de_faq/issues/34#issuecomment-169945484>.
>



-- 

Andrey Tkachenko
Software Engineer

<https://app.adjust.io/aowvd8?campaign=app_DE_iOS_launch&adgroup=email_signature&creative=&deep_link=home24%3A%2F%2F&fallback=http%3A%2F%2Fwww.home24.de%2Fapp%2F>

*www.home24.de* <http://www.home24.de/>

Home24 AG | Greifswalder Straße 212-213 | 10405 Berlin | Deutschland
tel: +49 17 999 31509 | mail: andrey.tkachenko@home24.de

Vorstand: Domenico Cipolla, Dr. Philipp Kreibohm, Constantin Eis, Axel
Hefer,
Vorsitzender des Aufsichtsrats: Alexander Samwer
Sitz Berlin | Eingetragen beim Amtsgericht Berlin (Charlottenburg), HRB
167157 B

Diese Nachricht (inklusive aller Anhänge) ist vertraulich. Sie darf
ausschließlich durch den vorgesehenen Empfänger
und Adressaten gelesen, kopiert oder genutzt werden. Sollten Sie diese
Nachricht versehentlich erhalten haben, bitten
wir Sie, den Absender (durch Antwort-E-Mail) hiervon unverzüglich zu
informieren und die Nachricht zu löschen. Jede
unerlaubte Nutzung oder Weitergabe des Inhalts dieser Nachricht, sei es
vollständig oder teilweise, ist unzulässig. Bitte
beachten Sie, dass E-Mail-Nachrichten an den Absender nicht für
fristgebundene Mitteilungen geeignet sind.
Fristgebundene Mitteilungen sind daher ausschließlich per Post oder per
Telefax zu übersenden.

**Comment by ewgRa** [comment]
через браузер "втихую" могут только те, кто имеет доступ на запись. Остальные только через PR.

я делаю через PR все, и всех призываю к этому.

Правка через браузер тоже может через PR проходить, там есть опция.

Просто о PR все узнают, а о "тихом" комите только те кто мониторит комиты, таких я думаю оч. мало.

**Comment by andreytkachenko-home24** [comment]
решается просто - убрать запись для всех, чтобы не мониторить.
С другой стороны - не production-ready код пишем, так что - на твой вкус.

2016-01-08 10:29 GMT+01:00 ewgRa <notifications@github.com>:

> через браузер "втихую" могут только те, кто имеет доступ на запись.
> Остальные только через PR.
>
> я делаю через PR все, и всех призываю к этому.
>
> Правка через браузер тоже может через PR проходить, там есть опция.
>
> Просто о PR все узнают, а о "тихом" комите только те кто мониторит комиты,
> таких я думаю оч. мало.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ewgRa/de_faq/issues/34#issuecomment-169945649>.
>



-- 

Andrey Tkachenko
Software Engineer

<https://app.adjust.io/aowvd8?campaign=app_DE_iOS_launch&adgroup=email_signature&creative=&deep_link=home24%3A%2F%2F&fallback=http%3A%2F%2Fwww.home24.de%2Fapp%2F>

*www.home24.de* <http://www.home24.de/>

Home24 AG | Greifswalder Straße 212-213 | 10405 Berlin | Deutschland
tel: +49 17 999 31509 | mail: andrey.tkachenko@home24.de

Vorstand: Domenico Cipolla, Dr. Philipp Kreibohm, Constantin Eis, Axel
Hefer,
Vorsitzender des Aufsichtsrats: Alexander Samwer
Sitz Berlin | Eingetragen beim Amtsgericht Berlin (Charlottenburg), HRB
167157 B

Diese Nachricht (inklusive aller Anhänge) ist vertraulich. Sie darf
ausschließlich durch den vorgesehenen Empfänger
und Adressaten gelesen, kopiert oder genutzt werden. Sollten Sie diese
Nachricht versehentlich erhalten haben, bitten
wir Sie, den Absender (durch Antwort-E-Mail) hiervon unverzüglich zu
informieren und die Nachricht zu löschen. Jede
unerlaubte Nutzung oder Weitergabe des Inhalts dieser Nachricht, sei es
vollständig oder teilweise, ist unzulässig. Bitte
beachten Sie, dass E-Mail-Nachrichten an den Absender nicht für
fristgebundene Mitteilungen geeignet sind.
Fristgebundene Mitteilungen sind daher ausschließlich per Post oder per
Telefax zu übersenden.

**Comment by ewgRa** [comment]
> решается просто - убрать запись для всех, чтобы не мониторить.

Доступ на прямую запись есть только у тебя, меня, @zvuki , @n0quarter , @Szaharov , @oleksiikyrychenko, всем остальным только форкать и слать PR. Если я заберу доступ на запись у всех - то мержить смогу только я, но это будет идти в разрез с желанием поддерживать faq не только своими силами, но и силами других заинтересованных людей, ибо так faq будет более живучим, качественным и независимым. Собственно те, у кого есть права на запись - могут мержить PR при желании, я только за.

Я был бы рад, если бы те кто имеет доступ на запись оформляли изменения через PR, чтобы все кто следит за репозиторием узнавали об изменениях, поэтому и призываю всех так делать. Чем больше людей будут знать об изменених, тем выше вероятность что они захотят внести правки, или обратят внимание на какие-то ошибки.

**Comment by n0quarter** [comment]
Обещаю только через PR

**Comment by ewgRa** [comment]
Добавил в первом приближении.

Надо красивый вывод теперь организовать плюс научить фейлить, сейчас все время проходит, даже если ошибки замечает.

**Comment by ewgRa** [comment]
Добавил правильный exit code, отображение только опечаток.

Осталось прогнать по всем файлам и исправить опечатки и возможно добавить свой словарь, чтобы можно было вносить туда заведомо правильные слова

**Comment by ewgRa** [comment]
вроде все добавил, в некоторых файлах остались опечатки, они поправятся в процессе
