### ISSUE TITLE
faq или wiki

### ISSUE THREAD

**Issue by ewgRa** [ewgRa/de_faq#50]
В общем назрела тема для коллективного разума.

@denyspopov предлагает изменения, которые я считаю не имеет смысла тащить в FAQ.

Примеры: 
https://github.com/ewgRa/de_faq/pull/44/files#diff-6387eaa0b429cf10e1fe48886a29e884R55
https://github.com/ewgRa/de_faq/pull/44/files#diff-6387eaa0b429cf10e1fe48886a29e884R83
https://github.com/ewgRa/de_faq/pull/44/files#diff-6387eaa0b429cf10e1fe48886a29e884R20

Мой основной аргумент: теряется фокус с информации по решению проблем на "мы вам сейчас все расскажем". FAQ потеряет свою ценность именно как выжимка из личного опыта и руководство к решению проблем. Будем говорить обо всем и ни о чем конкретном, плюс дублировать информацию, которую можно нагуглить при желании в wiki.

Собственно мое видение решения:
Если хочется wiki - можно создать отдельно и добавлять ссылки в релевантные разделы в faq, для желающих расширить свой кругозор или просвящаться.

**Comment by alexandr-g** [comment]
дак в самом гите есть wiki - может, скомбинировать их 

faq - держать чистым, а тем кто любит почитать - wiki

**Comment by trickii** [comment]
таки faq это ответы на вопросы, нужно сформулировать вопросы по темам и отвечать. Тогда будет конкретика, и в вики сдвинуть что есть сейчас, что тоже необходимо.

Быстрый ответ в FAQ, и описание в wiki
- Когда подавать налоговую декларацию
-> до мая текущего года

- Как получить Kontoauszug
-> в терминале, по почте, в онлайн кабинете банка

и т.д.

**Comment by denyspopov** [comment]
Да вики, конечно, нужно, сейчас почти никакой полезной информации нет здесь. Нужен ресурс, на который можно давать ссылки по различным вопросам (вместо того, чтобы раз за разом расписывать одно и то же).

**Comment by ewgRa** [comment]
какие мысли?

ping @andreytkachenko-home24 @n0quarter @oleksiikyrychenko @Szaharov

**Comment by n0quarter** [comment]
> Нужен ресурс, на который можно давать ссылки по различным вопросам (вместо того, чтобы раз за разом расписывать одно и то же).
http://asdCode.de ? я могу выдать админские доступы.

**Comment by oleksiikyrychenko** [comment]
Насчёт http://asdCode.de для статей. Есть уже сайт tupa-germania.ru. Вот пример статьи. http://www.tupa-germania.ru/avtomobil/obmen-prav-v-germanii.html
Точно хотите ещё один такой сайт? Информация там устаревает, попробуйте уговорить автора её обновить. Или можно её по комментариям поискать. Не очень удобно. Тем более уже есть.

С другой стороны гитхаб подход показал свои минусы тоже. Лично мое мнение - для правок запятых, которые тут всё бросились править, вместо того чтобы добавлять контент, пул реквест - лишний долгий шаг. Я бы даже дал право любителям орфографии коммитить прямо в мастер их правки. С другой стороны, из правки точно будут вызывать конфликты и будут мешать добавлять контент.

Итого, вики был бы удобнее, если мы считаем, что стилистика, отсутствие опечаток, запятые нам важнее быстроты наполнения контентом.

Что бы я сделал:
1. Сформулировать список вопросов FAQ. И соответственно тогда будет понятно, что в статье которая отвечает на вопрос "Как открыть банковский счёт" общая информация про IBAN может быть лишней. Хотя возможно в разделе "Банки" может быть как ответ на вопрос "Как открыть банковский счёт" так и ответ на вопрос "Как сделать банковский перевод". Просто вспомните какие вопросы постоянно задают в чате. Я не припоминаю, чтобы кто-то спрашивал про это в чате. Кстати, благодаря этому, можно было бы понять каких тем не хватает и коллективный разум помог бы заполнить пробелы. Например "Как оформить киндергельд?", "Как оформить гутшайн в садик".
2. Ввел мораторий на исправление опечаток, запятых и прочей стилистики при открытых пул реквестах с контентом. Если такие пул реквесты всё же будут открыты, они не будут приняты.
3. Быстрее принимать бы любые пул реквесты, которые хоть немного добавляют полезную информацию.

**Comment by ewgRa** [comment]
1. Согласен, список вопросов напрашивается. Буду стараться реорганизовывать постепенно.

2. > Если такие пул реквесты всё же будут открыты, они не будут приняты.
На мой взгляд это в корне неверно. Любая помощь ценна. Это как coding style, вроде штука не очень важная, но если не соблюдать, у всех портится настроение. Возможно такие правки стоит считать менее приоритетными по отношению к правкам контента, но не принимать их - точно неправильно. По крайней мере лично я готов тратить время на такие правки, так как считаю их важными. Иначе рано или поздно будем читать написанное и думать, где же стоит запятая в "казнить нельзя помиловать". Да и скоро количество таких правок существенно уменьшится. Добавлена автопроверка опечаток, раньше ни стилистике, ни запятым никто внимания вообще не уделял, если это будет делаться на постоянной основе - таких правок будет мало, а если они будут делаться на уровне просьб исправить в pull request - то вообще проблем не будет.

3. Тут согласен частично. Какая-то планка все равно должна быть, и все равно пул реквесты будут виснуть какое-то время, конфликты все равно будут, поэтому идея принимать по-быстрее чтобы избежать конфликтов - для меня выглядит не состоятельной, избежать конфликтов она если и поможет, то я уверен - породит другие проблемы.

**Comment by ewgRa** [comment]
ну и по конфликтам, я принципе готов их разруливать самостоятельно на этапе принятия PR, я вполне готов этим заниматься. Не думаю что их будет реально много.

**Comment by dstoianov** [comment]
а может лучше не `faq` а сайт на основе `github pages` как здесь описано https://github.com/ewgRa/de_faq/issues/74

**Comment by ewgRa** [comment]
@denyspopov в общем большинство за faq, как faq, и wiki как wiki.

То есть faq останется выжимкой опыта, который сложно нагуглить или разбросан по разным местам, и будет идти в сторону вопрос-ответ, а не wiki формата.

Если тебе интересно заняться именно wiki форматом, решай сам, на основе чего ты хочешь его делать. Если хочешь на основе https://github.com/ewgRa/de_faq/wiki - я дам доступ, не проблема. Но wiki часть github сильно урезана в плане командной работы, там нету Pull Request например насколько я знаю. Пиши в личку если решишь идти в эту сторону.

Мое личное мнение по wiki, независимо от того где wiki будет хоститься - это очень ресурсозатратно и я не вижу мотивации, которая бы лично меня сподвигла тратить время на ее развитие. Это мое личное мнение, я могу только пожелать удачи и буду помогать чем могу, если ты решишься этим заниматься.

FAQ появился как желание секономить время ответа на одни и те же вопросы, которые часто в чате задают, это хорошая мотивация, если ты часто отвечаешь на такие вопросы - ты экономишь прежде всего свое время. Один раз написал - и не надо по десять раз одно и то же переливать.
