### ISSUE TITLE
Хостинг на Github Pages

### ISSUE THREAD

**Issue by alabax** [ewgRa/de_faq#74]
Вопрос: есть ли желание перенести фак на гитхаб страницы так, чтобы нетехнические люди могли сообразить какая информация доступна? Сейчас выбор странички это гитхабовская таблица с именем файла.md, сообщением из коммита и свежестью. Терпимо, но непонятно тем, кто не пользовался гитхабом. Упростить жизнь можно через github pages с jekyll https://help.github.com/articles/using-jekyll-with-pages/ , при этом .md странички почти не изменятся, просто немного переедут в поддиректорию. Зато фак будет больше похож на сайт (http://phlow.github.io/feeling-responsive/ или http://lanyon.getpoole.com/ например). Я такую штуку недавно делал - в общем-то несложно, и я могу с этим помочь.
Что требуется сделать:
1. Самое сложное - общественность должна выбрать тему тут http://jekyllthemes.org/ или тут https://github.com/jekyll/jekyll/wiki/Themes
2. Я смержу тему и кастомизирую под работу с набором страниц вместо блоговидного представления.
3. Пулл реквест с этим делом помержится, но счастья не наступит.
4. Дело в том, что счастье наступает только когда репозиторий называется `username.github.io`. Соответственно, для ewgRa доступен только адрес http://ewgRa.github.io . Нужно будет выбрать новый username для фака, зарегистрировать новый аккаунт и создать соответствующий репозиторий, смержив туда ewgRa/de_faq.
В общем, ап ту ю гайс.

**Comment by AlexDenisov** [comment]
> Дело в том, что счастье наступает только когда репозиторий называется username.github.io

[User, Organization, and Project Pages](https://help.github.com/articles/user-organization-and-project-pages)

**Comment by alabax** [comment]
http://ewgra.github.io/de_faq ?

**Comment by dstoianov** [comment]
поддерживаю любую идею с хостингом, не важно какой он будет, не важно какой `url` главное что будет сайт :+1:

**Comment by ewgRa** [comment]
В принципе это все реализуемо, единственный момент - как там рабоает "Edit" кнопка? Это будет какой-то анонимный pull request?

Основной негативный момент, который хотелось бы избежать - это чтобы читатели понимали, что они могут не только почитать, но и внести изменения. На github это очевидно и занимает немного кликов, а вот на таком сайте уже неочевидно и посложнее.

**Comment by l13t** [comment]
ИМХО, для нетехнических людей правильнее всего на главной написать, что если есть пожелания/предложения/правки - пишите на такой-то почтовый ящик.

По поводу домена: а что если настроить CNAME на ewgra.github.io ?
Если я правильно понял ссылку ниже, то гитхаб умеет так работать: https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/

Ну и как вариант - могу разместить доку у себя на сервере. Но необходимо как-то это все красиво оформить и автоматически обновлять.

**Comment by l13t** [comment]
http://de-faq.lo0.org.ua/

навскидку сделано за 10 минут при помощи mkdocs: http://www.mkdocs.org/

**Comment by ewgRa** [comment]
@l13t выглядит хорошо. Так как все материалы используются свободно, каждый может делать с информацией что хочет, в том числе ты можешь сделать такую штуку и я с удовольствием приму PR в README со ссылкой на такой ресурс.

Единственное, что я уже говорил, я бы хотел видеть там ссылку - "edit me", которая способствует более активному участию в добавлении-измении информации. Но учитывая, что любой может сделать такой ресурс на основе FAQ и даже не обращать внимание на базовый репозиторий, контролировать я это все равно не смогу (более того, не хочу :)), поэтому в целом у меня никаких возражений нет и быть не может. Если у кого-то есть силы и желание поддерживать такой ресурс - я думаю это будет только на пользу всем. Возможно на этом можно что-то даже заработать, размещая там какую-то рекламу и это будет мотивировать владельца ресурса его поддерживать и улучшать сам базовый репозиторий.


Суммируя: если есть желание сделать это сторонним ресурсом - все только поддержат.

Этот issue я закрываю, если кто решится - можно создать PR в README.md со ссылкой на такой ресурс.
